development:
  dialect: "mysql"
  database: "vzk"
  host: "localhost"
  port: "3306"
  user: "root"
  password: ""
#  database: "vzk"
#  host: "localhost"
#  port: "3306"
#  user: "sadegh"
#  password: "sjegcYhj7gfdd3r5yj3uyUy4"

test:
  dialect: "mysql"
  #
  # You can use a single URL string for the same configuration:
  #
  #url: "mysql://root:root@(localhost:3306)/project_test?parseTime=true&multiStatements=true&readTimeout=3s"
  #
  # Note that if you use `url`, other configurations are silently ignored.
  # In this case, the URL must contain all required connection parameters.
  #
  database: "project_test"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

production:
  #
  # You can also use environmental variables to override values in this config.
  #
  #url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/project_production?parseTime=true&multiStatements=true&readTimeout=3s"}}
  #
  dialect: "mysql"
  database: "antilicense"
  host: {{envOr "DATABASE_HOST" "localhost"}}
  port: {{envOr "DATABASE_PORT" "3306"}}
  user: {{envOr "DATABASE_USER" "sadegh"}}
  password: {{envOr "DATABASE_PASSWORD" "sjegcYhj7gfdd3r5yj3uyUy4"}}
  #
  # And you can also override connection parameters by setting it under options.
  #
  #options:
  #  parseTime: true
  #  multiStatements: true
  #  readTimeout: 3s
  #  encoding: "utf8mb4_general_ci"
  #
  # CAUTION!
  #   `parseTime` and` multiStatements` must be set to `true` to work properly.
  #   If you are not sure, do not change (or set) these values.
