package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/sadegh-shahbazi/vzk/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Anti)
// DB Table: Plural (antis)
// Resource: Plural (Antis)
// Path: Plural (/antis)
// View Template Folder: Plural (/templates/antis/)

// AntisResource is the resource for the Anti model
type AntisResource struct {
	buffalo.Resource
}

// List gets all Antis. This function is mapped to the path
// GET /antis
func (v AntisResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	antis := &models.Antis{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Antis from the DB
	if err := q.All(antis); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, antis))
}

// Show gets the data for one Anti. This function is mapped to
// the path GET /antis/{anti_id}
func (v AntisResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Anti
	anti := &models.Anti{}

	// To find the Anti the parameter anti_id is used.
	if err := tx.Find(anti, c.Param("anti_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, anti))
}

// New renders the form for creating a new Anti.
// This function is mapped to the path GET /antis/new
func (v AntisResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Anti{}))
}

// Create adds a Anti to the DB. This function is mapped to the
// path POST /antis
func (v AntisResource) Create(c buffalo.Context) error {
	// Allocate an empty Anti
	anti := &models.Anti{}

	// Bind anti to the html form elements
	if err := c.Bind(anti); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(anti)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, anti))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "anti.created.success"))
	// and redirect to the antis index page
	return c.Render(201, r.Auto(c, anti))
}

// Edit renders a edit form for a Anti. This function is
// mapped to the path GET /antis/{anti_id}/edit
func (v AntisResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Anti
	anti := &models.Anti{}

	if err := tx.Find(anti, c.Param("anti_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, anti))
}

// Update changes a Anti in the DB. This function is mapped to
// the path PUT /antis/{anti_id}
func (v AntisResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Anti
	anti := &models.Anti{}

	if err := tx.Find(anti, c.Param("anti_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Anti to the html form elements
	if err := c.Bind(anti); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(anti)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, anti))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "anti.updated.success"))
	// and redirect to the antis index page
	return c.Render(200, r.Auto(c, anti))
}

// Destroy deletes a Anti from the DB. This function is mapped
// to the path DELETE /antis/{anti_id}
func (v AntisResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Anti
	anti := &models.Anti{}

	// To find the Anti the parameter anti_id is used.
	if err := tx.Find(anti, c.Param("anti_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(anti); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "anti.destroyed.success"))
	// Redirect to the antis index page
	return c.Render(200, r.Auto(c, anti))
}
